### ISSUE TITLE
Add the ability to refund participants

### ISSUE THREAD

**Issue by ryanadanderson** [NullVoxPopuli/aeonvera#116]
I have a pass from an event (SwingIN) that I just remembered about. I asked hillary what to do and we realized there's no "refund" ability. I bet you'd also want to be able to refund $X depending on your refund policy.

**Comment by NullVoxPopuli** [comment]
yeah, until I get that implemented, you'll have to issue refunds directly through stripe.

**Comment by NullVoxPopuli** [comment]
be sure give an option to specify an amount, or percentage.

**Comment by NullVoxPopuli** [comment]
Added in #737
