### ISSUE TITLE
Prize code should adjust with price increases

### ISSUE THREAD

**Issue by bradke** [NullVoxPopuli/aeonvera#119]
If discount/prize code is for a specific package that will be going through price tier increases, the value should increase with it. (i.e. code distributed when price was $89, now price is $109, code should still cover $109) Different than 100% discount, which would end up including shirt or comp purchases.

**Comment by NullVoxPopuli** [comment]
This'll be solved when discounts can be assigned to a particular item. (coming soon, probably this week). Ya'd just set 100% discount, and set it to only take 100% of the selected item.

**Comment by NullVoxPopuli** [comment]
Implemented in the backend, but not yet in UI

**Comment by NullVoxPopuli** [comment]
well, that was more code than I thought it would be...
