### ISSUE TITLE
Require "I have read and agree to terms and conditions" box to be checked to complete registration.

### ISSUE THREAD

**Issue by bradke** [NullVoxPopuli/aeonvera#121]
"terms and conditions" should link to webpage or PDF document listing the event's liability waver, code of conduct, etc.

**Comment by NullVoxPopuli** [comment]
Does SwingIN have one of those?

**Comment by bradke** [comment]
Not yet, but I'd like to see it happen. I know we discussed something
similar in the past, but never made it happen...something to do with
Caitlin liking paper I believe. Anywho, we haven't actually printed waivers
for people to sign, so a digital agreement is better than nothing.

The thought was mostly triggered by all this code of conduct hubbub after
Steven Mitchell was outed for being a creep. I think it's something SwingIN
needs to adopt and I think a digital signature is best. No paperwork to get
lost.
ᐧ

2015-01-23 19:27 GMT-05:00 L. Preston Sego III <notifications@github.com>:

> Does SwingIN have one of those?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NullVoxPopuli/swing-dance-registration-system/issues/121#issuecomment-71289755>
> .
>



-- 
*Brittany*
Molecular Biologist, Dow AgroSciences
Instructor, Naptown Stomp Lindy Hop Society

Geneticist by day, dancer by night, but only one pays the bills.

**Comment by NullVoxPopuli** [comment]
agreed. If you can get something or find something, I'll make this happen. :-)

**Comment by NullVoxPopuli** [comment]
TODO: make users check this for AE's ToS

**Comment by NullVoxPopuli** [comment]
Also add this to organizations --- require per order.

**Comment by NullVoxPopuli** [comment]
Estimation: 4 hours

**Comment by NullVoxPopuli** [comment]
moved to gitlab
