### ISSUE TITLE
Level Placement System for instructors

### ISSUE THREAD

**Issue by NullVoxPopuli** [NullVoxPopuli/aeonvera#147]
Apparently Lindy focus has this.

**Comment by NullVoxPopuli** [comment]
From Ryan:

https://organizersdilemma.wordpress.com/2013/01/14/lindy-focus-auditions/

This might help ya out

Basically they have a lower limit of how many people need to view the dancers. each dancer is assigned a number on a scale from low to high.

Then, you put in the size of the classes you want, and the program would sort people out to match you close to your peers

For instance, Jo, Faulty, and Dax rate the person as 3, 4, and 3 respectively. It takes an average and places that person in order of everyone else. Then it makes the cuts.

I haven't specifically seen it  I wish though. That'd be neat

**Comment by NullVoxPopuli** [comment]
level testees are identified by bid numbers

**Comment by ryanadanderson** [comment]
Bid#, Rank1, Rank2, Rank3,...,average
