### ISSUE TITLE
Allow manual entry of hosts

### ISSUE THREAD

**Issue by bradke** [NullVoxPopuli/aeonvera#176]
You know, for the people who don't originally sign up and I have to go convince later one. This will tie into another request of mine about calculating available space & wait-list notifications.

**Comment by bradke** [comment]
Also allow the organizers to manually change how many spaces a host can offer (or make it a feature in the UI for attendees? that's probably more difficult)

**Comment by NullVoxPopuli** [comment]
This will be interesting for when a manual entered person registered (if they register). I could do some things with email or phone number to match them up.

**Comment by bradke** [comment]
by email would probably be the easiest & the system would have to be smart enough to ignore periods or differing capitalization. I don't trust registrants to properly spell, capitalized, or format anything else...although i guess it's always possible the organizer might have entered the email wrong when they manually entered it....i feel like that's less likely though

**Comment by NullVoxPopuli** [comment]
I don't trust silly formatting either. But I can force them to enter a valid email. And then I can just compare the lowercase version of both without periods

**Comment by NullVoxPopuli** [comment]
Step 1 done and deployed. Just wanted to get the housing provision stuff collected. before the more complex stuff that uses the HousingProvision and HousingRequest objects
