### ISSUE TITLE
Create an automatic wait-list notification

### ISSUE THREAD

**Issue by bradke** [NullVoxPopuli/aeonvera#178]
Have the system tally how many spaces versus how many spaces have been requested (irrespective of whether or not housing has been assigned) and shoot back an email to the registrant notifying them they are on a wait-list for housing once there are more requests than there are available spaces.

Also, make the names on the wait-list visible to the organizer(s).

**Comment by NullVoxPopuli** [comment]
this should probably be #2 after swingin registration opens
