### ISSUE TITLE
Have a "stop bugging us" statement about housing requests

### ISSUE THREAD

**Issue by bradke** [NullVoxPopuli/aeonvera#179]
Maybe this is just a personal thing and not important to the entire registration system, but allow organizers to include a statement in the instructions for housing that attendees will be notified well in advanced if they cannot be placed in housing...and it's pointless to ask us any details in advance! :) </rant>

**Comment by NullVoxPopuli** [comment]
relates to #180

**Comment by NullVoxPopuli** [comment]
for now, this is going to be an addition to the event configuration. 

Later, I can see customizing emails being pretty powerful.

**Comment by NullVoxPopuli** [comment]
Relates to #209
