### ISSUE TITLE
allow registrant to purchase more than one of each item

### ISSUE THREAD

**Issue by bradke** [NullVoxPopuli/aeonvera#188]
This is actually from Ryan Anderson. He likes to buy multiple passes at an early price & then make them available to other members of his scene. I guess that would involve a bunch of pass transfers, but he'd like to see a way for someone to buy multiple weekend passes if they want.

**Comment by NullVoxPopuli** [comment]
interesting. I'll have to think about how that would work.

**Comment by NullVoxPopuli** [comment]
Now that everything is going to be an order-line-item, it should be possible to do this

**Comment by NullVoxPopuli** [comment]
done!
