### ISSUE TITLE
Gift Certificates should be purchaseable 

### ISSUE THREAD

**Issue by NullVoxPopuli** [NullVoxPopuli/aeonvera#190]
These are like buying a discount, not exactly a pass? maybe the option should be to cover a full pass or a dollar amount.

**Comment by NullVoxPopuli** [comment]
@bradke, do you remember what the requirements are on this? how it would work? what a gift certificate even means? how it can be used?

**Comment by bradke** [comment]
Someone could purchase a gift certificate (or really, a gift code) of a specific amount anytime before registration opens or even during registration. They could then give that code to someone as a gift or use it themselves, although I don't know why they would do the latter. 

Brittany
