### ISSUE TITLE
glitch with discounts

### ISSUE THREAD

**Issue by bradke** [NullVoxPopuli/aeonvera#237]
When reopening a discount to edit it, I noticed the dollars off/percent off reverts back to dollars off every time it's opened. Minor nuisance, but it might trip someone up if they're not paying attention.

**Comment by bradke** [comment]
Also, it would be nice if the restrictions automatically appeared when creating a discount, instead of having to save it and then go back and edit it again. :)

But seriously though, super impressed with all of the functionality.

**Comment by NullVoxPopuli** [comment]
yeah, I'm planning on re-doing all of the UI over the next 3 or 4 months. Should be much quicker, and easier to customize. 

If you cancel editing, does the list of discounts show the correct dollar / percent value?

**Comment by bradke** [comment]
It does

2015-06-04 10:01 GMT-04:00 L. Preston Sego III <notifications@github.com>:

> yeah, I'm planning on re-doing all of the UI over the next 3 or 4 months.
> Should be much quicker, and easier to customize.
>
> If you cancel editing, does the list of discounts show the correct dollar
> / percent value?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NullVoxPopuli/aeonvera/issues/237#issuecomment-108908282>
> .
>



-- 
*Brittany*
Molecular Biologist
Instructor, Naptown Stomp Lindy Hop Society

Geneticist by day, dancer by night, but only one pays the bills.

**Comment by NullVoxPopuli** [comment]
This is fixed in AE v1, to be released soonish
