### ISSUE TITLE
Upcoming Events aren't coming up

### ISSUE THREAD

**Issue by ryanadanderson** [NullVoxPopuli/aeonvera#352]
Sierra Anderson found this on her account. It's also not working on mine. We're both going for SwingIN. Good luck!

![image](https://cloud.githubusercontent.com/assets/10438465/9558424/8bc8ec7c-4db3-11e5-980b-c213ea2b6cf0.png)

**Comment by NullVoxPopuli** [comment]
on it!

**Comment by ryanadanderson** [comment]
:+1:
