### ISSUE TITLE
Editing Discount restriction positioning 

### ISSUE THREAD

**Issue by ryanadanderson** [NullVoxPopuli/aeonvera#402]
It might be better if these were all on their own line. The boxes are confusing. 

![image](https://cloud.githubusercontent.com/assets/10438465/9797336/8b317c6a-57c8-11e5-83f0-1f59e2392314.png)

**Comment by NullVoxPopuli** [comment]
To be addressed in AE v1

**Comment by NullVoxPopuli** [comment]
![image](https://cloud.githubusercontent.com/assets/199018/14211318/574c4ec4-f7fb-11e5-8fee-e25b1f03ec23.png)
