### ISSUE TITLE
Editing discount page does not remember "Kind"

### ISSUE THREAD

**Issue by ryanadanderson** [NullVoxPopuli/aeonvera#403]
Every time I modify this, the Kind resorts to the $ off, not % off like I wanted it to be.

![image](https://cloud.githubusercontent.com/assets/10438465/9797402/ea74c47a-57c8-11e5-8e03-93ff4d2a1cd5.png)

**Comment by NullVoxPopuli** [comment]
fixed in the master branch (to be released before the end of april)
