### ISSUE TITLE
Preview Your Ticket Costs

### ISSUE THREAD

**Issue by ryanadanderson** [NullVoxPopuli/aeonvera#483]
The check box activates once and freezes, once activated it is visually shown as false (not true), and can't be clicked again to undo. This is fixed by changing the ticket price box.

I'm using chrome 48.0.2564.109 m

<3 Ryan

![image](https://cloud.githubusercontent.com/assets/10438465/13087326/51352934-d4b5-11e5-8f17-28f46541163c.png)

**Comment by NullVoxPopuli** [comment]
Thanks for the report! I'll take a look at this soon!

**Comment by ryanadanderson** [comment]
It's a cool feature! It makes the end user in me happy.

**Comment by NullVoxPopuli** [comment]
The fix for this will hopefully be released within a month.
