### ISSUE TITLE
Migrate to SparkPost

### ISSUE THREAD

**Issue by NullVoxPopuli** [NullVoxPopuli/aeonvera#492]
Mandrill is no longer a full service, but an addon to paid mailchimp subscribers

**Comment by yepher** [comment]
SparkPost has a straight forward [API](https://github.com/SparkPost) and has a [free](https://www.sparkpost.com/pricing) tier that my be a suitable alternative.

**Comment by NullVoxPopuli** [comment]
ok thanks! I'll look in to that. I just looked at SendGrid's website, and they don't have a free tier either.

**Comment by yepher** [comment]
For your reference here is the SparkPost Ruby API: 
    https://github.com/SparkPost/ruby-sparkpost

**Comment by NullVoxPopuli** [comment]
I've added this to both my production and staging domains. aeonvera.com and aeonvera-staging.work.

thanks!
