### ISSUE TITLE
Require password to delete account. 

### ISSUE THREAD

**Issue by ryanadanderson** [NullVoxPopuli/aeonvera#537]
I didn't click the confirmation but it didn't seem that I needed to enter a password to delete the account.

https://aeonvera.com/user/edit

**Comment by NullVoxPopuli** [comment]
that's a good idea, don't want to accidentally delete the account.

**Comment by NullVoxPopuli** [comment]
Note that accounts aren't permanently deleted. So, Imma de-prioritize this a bit.
