### ISSUE TITLE
Send email notification if account is canceled

### ISSUE THREAD

**Issue by ryanadanderson** [NullVoxPopuli/aeonvera#538]
I didn't test this, but it'd be nice to know that I cancelled my account, just in cause something nefarious is going on.

**Comment by NullVoxPopuli** [comment]
good idea

**Comment by NullVoxPopuli** [comment]
![image](https://cloud.githubusercontent.com/assets/199018/15099459/8c44f4a6-1523-11e6-84c5-22d029d5f622.png)

**Comment by NullVoxPopuli** [comment]
I'll be releasing this in about 15-20 minutes
