### ISSUE TITLE
events - new - Check Boxes do not follow text to new line. 

### ISSUE THREAD

**Issue by ryanadanderson** [NullVoxPopuli/aeonvera#539]
Housing and Housing nights of event set up travel around a little and can lead to errors and confusion.
 
https://www.aeonvera.com/hosted_events/new

![image](https://cloud.githubusercontent.com/assets/10438465/14213384/ac99e31e-f805-11e5-9747-3ebb73199ac7.png)

![image](https://cloud.githubusercontent.com/assets/10438465/14213407/cee8b4fe-f805-11e5-8e64-03cc1afafaee.png)

**Comment by NullVoxPopuli** [comment]
thanks! housing nights are removed in the upcoming release (AE v1) https://github.com/NullVoxPopuli/aeonvera/milestones/Transition%20the%20UI%20to%20Ember%20(AE%20v1)
