### ISSUE TITLE
Label lines to "event starts at" and "event ends at" to ensure clarity

### ISSUE THREAD

**Issue by ryanadanderson** [NullVoxPopuli/aeonvera#540]
![image](https://cloud.githubusercontent.com/assets/10438465/14213509/4ec1e808-f806-11e5-9790-6ab9ec2647b6.png)

**Comment by NullVoxPopuli** [comment]
How do you feel about the AE v1 left/right alignment?

![image](https://cloud.githubusercontent.com/assets/199018/14215787/270f4a96-f813-11e5-8e55-ae4deee113cf.png)

This will be released in the middle of April

**Comment by NullVoxPopuli** [comment]
actually, I guess what your reporting is just the verbiage, 'Event Starts at' vs 'Starts at'

I can do that real easy.

**Comment by NullVoxPopuli** [comment]
@ryanadanderson thoughts on this? 
![image](https://cloud.githubusercontent.com/assets/199018/14215852/a522608a-f813-11e5-935c-efde67b9932f.png)

**Comment by NullVoxPopuli** [comment]
I'm gonna close this out, since I think this is a good change. :-) Thanks @ryanadanderson

**Comment by ryanadanderson** [comment]
Awesome! I think it's much more clear now.

I like the left to right stuff. I know that some might miss it. Would
adding a color change in box 2 (Short Description) if people skip from box
1 (event name) to box 3 (Location) to bring to their attention that they
might have missed a box. Or maybe a small note upon saving that say "hey,
you didn't fill out {category or categories}. The data was saved but you
might want to fill out the empty boxes."

Ryan
