### ISSUE TITLE
Manually added housing requests do not show up in csv export

### ISSUE THREAD

**Issue by bradke** [NullVoxPopuli/aeonvera#817]

**Comment by bradke** [comment]
also, they don't sort in the "registered at" column in aeonvera, the other columns seem to be working fine

**Comment by NullVoxPopuli** [comment]
thanks for the report!

**Comment by NullVoxPopuli** [comment]
So, I looked in to this, and I see the manually added people. Their name is under a different column from the other people.

This is confusing and needs to change, but the reason why is that the names are stored in different locations. For manually added people, the names are on the housing request itself, and for actually registered people, columns are either directly on the attendance record, or are aliased to the user..

See: #819
