### ISSUE TITLE
Could not download source map specified in the minified js file

### ISSUE THREAD

**Issue by NullVoxPopuli** [NullVoxPopuli/aeonvera#823]
View details in Rollbar: [https://rollbar.com/nullvoxpopuli/aeonvera/items/156/](https://rollbar.com/nullvoxpopuli/aeonvera/items/156/)

```
Could not download source map specified in the minified js file
```

**Comment by lydia-schow** [comment]
@NullVoxPopuli How did you end up fixing this? I just installed Rollbar yesterday and I'm running into the same error.

**Comment by NullVoxPopuli** [comment]
I do not remember :sweat_smile: that's nearly 8 years ago now :upside_down_face: 

Apologies!

**Comment by lydia-schow** [comment]
Aw, bummer. Thanks for the reply, though.
