### ISSUE TITLE
Can't see multiple housing requests under one registration

### ISSUE THREAD

**Issue by bradke** [NullVoxPopuli/aeonvera#845]
Liz Schoenfelder registered and paid for her and Chris, but only Liz showed up in housing requests. (thankfully I caught this one early on because I know them, but who knows, it'll probably happen again...I think Dan Hoy and Gail Clendenin did it to me last year as well)

**Comment by NullVoxPopuli** [comment]
I actually *just* thought of this as a problem as I've been thinking about https://github.com/NullVoxPopuli/aeonvera/issues/832 and https://github.com/NullVoxPopuli/aeonvera/issues/831

The fact that people have sometimes accidentally and intentionally registered for two people under one account this go-around is amusing.

**Comment by NullVoxPopuli** [comment]
I think in the future, EVERYTHING is going to be tied to order line items

**Comment by NullVoxPopuli** [comment]
I believe this issue is resolved now :-)
