### ISSUE TITLE
In-system chat/messaging for hosts/guests

### ISSUE THREAD

**Issue by bradke** [NullVoxPopuli/aeonvera#877]
This sounds really messy to code, but it would allow for "message read" notifications, so people actually know the info has been seen. Automatically include housing coordinator in every thread (but silence notifications)? Allow for group host/guest(s) as well as PM? (From Lauren Phillips, Chicago)

**Comment by NullVoxPopuli** [comment]
I think I have to do something similar for work. But, it's a solved problem, so I don't have a whole lot to figure at. :-)
